name: Weekly Update
on:
  schedule:
    - cron: '0 2 * * 1'  # 每周一北京时间早上10点(UTC+8对应UTC时间2点)
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run WRC scraper
      run: python src/wrc/wrc.py
    - name: Run F1 scraper
      run: python src/f1/f1.py
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add release/
        git commit -m "Auto update race data [skip ci]" || echo "No changes to commit"
        git push