name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Generate ICS files
        run: |
          pip install -r requirements.txt
          python src/wrc/wrc.py
          python src/f1/f1.py
          python src/csgo/csgo.py
          python src/dota2/dota2.py
          
      - name: Create index.html
        run: |
          cat <<EOF > index.html
          <!DOCTYPE html>
          <html>
          <head>
              <title>日历订阅</title>
          </head>
          <body>
              <h1>日历订阅</h1>
              <ul>
                  <li><a href="release/wrc/wrc.ics">WRC赛事日历</a></li>
                  <li><a href="release/csgo/csgo.ics">csgo赛事日历</a></li>
                  <li><a href="release/f1/f1.ics">F1赛事日历</a></li>
                  <li><a href="release/dota2/dota2.ics">dota2赛事日历</a></li>
              </ul>
          </body>
          </html>
          EOF
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
